version: '3'

services:
  db:
    image: "postgres:11"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
  web:
    build: .
    command: python /trading_platform/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/trading_platform
    ports:
      - 8000:8000
    env_file:
      ./.env.dev
    depends_on:
      - db
  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - .redis_data:/data
  celery:
    build: .
    volumes:
      - .:/src
    command: celery -A trading_platform worker -B -l info
    env_file:
      - .env.dev
    links:
      - redis
    depends_on:
      - db
      - web
      - redis

volumes:
  postgres_data: