version: '3'

services:
  db:
    image: "postgres:11"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  web:
    build: .
    command: python /trading_platform/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/trading_platform
    ports:
      - 8000:8000
    env_file:
      ./.env.dev
    depends_on:
      - db

volumes:
  postgres_data: